/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1008007
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Consulta = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Login = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        Senha = new javax.swing.JPasswordField();

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 70, 30));

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, -1, 30));

        Consulta.setText("Consulta");
        Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 80, 30));

        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, 30));

        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel3.setText("ENTRAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 140, 80));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, -1, -1));

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Login", "Senha"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 340, 120));
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
UsuarioDAO crud = new UsuarioDAO();
    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
   String login = Login.getText();
    String senha = new String(Senha.getPassword());

    UsuarioDAO crud = new UsuarioDAO(); // instância necessária

    if (crud.autenticar(login, senha)) {
        lblResultado.setText("Login bem-sucedido!");
        dispose();
    } else {
        lblResultado.setText("Login inválido.");
    }

     
    }//GEN-LAST:event_EntrarActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String login = Login.getText();
    String senha = new String(Senha.getPassword());

    UsuarioDAO crud = new UsuarioDAO(); // ou usar o existente fora do método

    if (crud.Cadastrar(login, senha)) {
        lblResultado.setText("Usuário cadastrado!");
    } else {
        lblResultado.setText("Erro ao cadastrar.");
    }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int linha = tabelaUsuarios.getSelectedRow();
    if (linha != -1) {
        String login = tabelaUsuarios.getValueAt(linha, 0).toString();
        UsuarioDAO crud = new UsuarioDAO();
        if (crud.deletar(login)) {
            JOptionPane.showMessageDialog(this, "Usuário deletado!");
            Atualizar.doClick(); // Atualiza tabela
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao deletar.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um usuário.");
    }      // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        int linha = tabelaUsuarios.getSelectedRow();
    if (linha != -1) {
        String loginAntigo = tabelaUsuarios.getValueAt(linha, 0).toString();
        
        String novoLogin = JOptionPane.showInputDialog(this, "Novo login:", loginAntigo);
        String novaSenha = JOptionPane.showInputDialog(this, "Nova senha:");
        
        if (novoLogin != null && novaSenha != null && !novoLogin.isEmpty() && !novaSenha.isEmpty()) {
            UsuarioDAO crud = new UsuarioDAO();
            if (crud.atualizarUsuario(loginAntigo, novoLogin, novaSenha)) {
                JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso!");
                Atualizar.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um usuário.");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaActionPerformed
    UsuarioDAO crud = new UsuarioDAO();
    List<String[]> lista = crud.listarUsuarios();
    
    DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();
    modelo.setRowCount(0); // Limpa a tabela
    
    
    for (String[] u : lista) {
        modelo.addRow(new Object[]{u[0], u[1]});
    }        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Consulta;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Entrar;
    private javax.swing.JTextField Login;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
